apiVersion: v1
kind: Service
metadata:
  name: angular-service
spec:
  type: {{ .Values.angular.service.type }}
  ports:
  - port: {{ .Values.angular.service.port }}
    targetPort: 80
  selector:
    app: autobid-ui 