apiVersion: apps/v1
kind: Deployment
metadata:
  name: autobid-ui-angular
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autobid-ui
  template:
    metadata:
      labels:
        app: autobid-ui
    spec:
      containers:
      - name: autobid-ui-angular
        image: {{ .Values.angular.image }}
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: {{ .Values.angular.service.port }}