apiVersion: apps/v1
kind: Deployment
metadata:
  name: autobid-api-aspnetcore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autobid-api
  template:
    metadata:
      labels:
        app: autobid-api
    spec:
      containers:
        - name: autobid-api-aspnetcore
          image: {{ .Values.dotnet.image }}
          env:
          - name: ConnectionStrings__DefaultConnection
            value: {{ .Values.dotnet.env.ConnectionStrings__DefaultConnection }}
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: {{ .Values.dotnet.service.port }}