apiVersion: v1
kind: Service
metadata:
  name: autobid-api-service
spec:
  type: {{ .Values.dotnet.service.type }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
  selector:
    app: autobid-api