apiVersion: v1
kind: Service
metadata:
  name: dotnet-service
spec:
  type: {{ .Values.dotnet.service.type }}
  ports:
  - port: {{ .Values.dotnet.service.port }}
    targetPort: 5000
  selector:
    app: dotnet-sdk