angular:
  image: node:18.1
  service:
    type: ClusterIP
    port: 4200

dotnet:
  image: mcr.microsoft.com/dotnet/sdk:8.0
  service:
    type: ClusterIP
    port: 5013

postgres:
  image: postgres:latest
  service:
    type: ClusterIP
    port: 5432